from enum import Enum


class ResponseSignal(Enum):
   FILE_VALIDATE_SUCESS="file_validate_successfuly"
   FILE_TYPE_NOT_SUPPORTED="FILE_TYPE_NOT_SUPPORTED"
   FILE_SIZE_EXCEEDED="FILE_SIZE_EXCEEDED"
   FILE_UPLOADED_SUCCESS="FILE_UPLOADED_SUCCESS"
   FILE_UPLOADED_FAILED="FILE_UPLOADED_FAILED"